# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui0.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(983, 766)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")

        self.rgbLabel = QtWidgets.QLabel(self.centralwidget)
        self.rgbLabel.setText("")
        self.rgbLabel.setObjectName("rgbLabel")
        self.gridLayout.addWidget(self.rgbLabel, 0, 0, 1, 1)

        self.depthLabel = QtWidgets.QLabel(self.centralwidget)
        self.depthLabel.setText("")
        self.depthLabel.setObjectName("depthLabel")
        self.gridLayout.addWidget(self.depthLabel, 0, 1, 1, 1)

        self.irLabel = QtWidgets.QLabel(self.centralwidget)
        self.irLabel.setText("")
        self.irLabel.setObjectName("irLabel")
        self.gridLayout.addWidget(self.irLabel, 1, 0, 1, 1)

        self.label4 = QtWidgets.QLabel(self.centralwidget)
        self.label4.setText("")
        self.label4.setObjectName("label4")
        self.gridLayout.addWidget(self.label4, 1, 1, 1, 1)
        
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.patientIDLabel = QtWidgets.QLabel(self.centralwidget)
        self.patientIDLabel.setObjectName("patientIDLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.patientIDLabel)
        self.patientIDEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.patientIDEdit.setObjectName("patientIDEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.patientIDEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.recordButton = QtWidgets.QPushButton(self.centralwidget)
        self.recordButton.setObjectName("recordButton")
        self.verticalLayout.addWidget(self.recordButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 983, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Data Acquisition"))
        self.patientIDLabel.setText(_translate("MainWindow", "病人ID"))
        self.recordButton.setText(_translate("MainWindow", "开始录制"))
